spring:
  datasource:
    url: jdbc:mysql://120.24.45.186:3307/db_smart?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root

logging:
  level:
    com.smart.rest: debug